import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    overlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        padding: 20,
    },
    content: {
        backgroundColor: '#f9f9f9',
        borderRadius: 15,
        padding: 20,
        maxHeight: '80%',
        gap: 10,
    },
    title: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 15,
        textAlign: 'center',
        marginTop: 40,
    },
    item: {
        padding: 12,
        borderWidth: 1,
        borderColor: '#878787',
        marginTop: 10,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderRadius: 5,
    },
    itemSelected: {
        borderWidth: 1,
        borderColor: '#309130ff',
        backgroundColor: '#f3f8f2ff',
    },
    itemText: {
        fontSize: 16,
    },
    confirmBtn: {
        marginTop: 15,
        padding: 8,
        borderRadius: 8,
        alignItems: 'center',
        backgroundColor: '#c02623',
        height: 50,
        justifyContent: 'center',
    },
    confirmText: {
        color: 'white',
        fontWeight: 'bold',
    },
    closeBtn: {
        marginTop: 10,
        alignItems: 'center',
        padding: 10,
        position: 'absolute',
        marginLeft: 10,
        alignItems: 'center',
        justifyContent: 'center',
        display: 'flex',
        flexDirection: 'row',
        gap: 10,
    },
    closeText: {
        color: '#af1919ff',
        fontSize: 14,
        fontWeight: 'bold',
    },
    specialBtn: {
        marginTop: 5,
        marginBottom: 5,
        padding: 8,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#f8f9fa',
    },
    specialText: {
        fontWeight: '600',
    },
    debugText: {
        fontSize: 12,
        color: '#666',
        textAlign: 'center',
        fontStyle: 'italic',
    },
});
